# Project Name
TARGET = overdrive

DEBUG = 1
OPT = -Og

# Sources
CPP_SOURCES = overdrive.cpp

# Include Paths
INC_DIRS = -I../../Inc

# Library Locations
LIBDAISY_DIR = ../../../Libraies/libDaisy
DAISYSP_DIR = ../../../Libraries/DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
